<div data-proud-page><main class="mx-auto max-w-4xl px-4 py-5 sm:px-6 sm:py-8">
    <header><p class="text-xs font-bold uppercase tracking-wider text-amber-700 dark:text-amber-400">Visual · Rilis 3</p><h1 class="mt-1 text-3xl font-black tracking-tight">Studio Video</h1><p class="mt-2 max-w-xl text-sm leading-6 text-slate-600 dark:text-zinc-400">Buat MP4 vertikal 9:16 dari foto final. Durasi mengikuti template dan render berjalan di antrean.</p></header>
    @if(session('video-sukses'))<div role="status" class="mt-4 rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950 dark:text-emerald-200">{{ session('video-sukses') }}</div>@endif
    @error('video')<div role="alert" class="mt-4 rounded-xl border border-red-300 bg-red-50 px-4 py-3 text-sm font-medium text-red-900 dark:border-red-900 dark:bg-red-950 dark:text-red-200">{{ $message }}</div>@enderror
    <section class="mt-6 rounded-2xl border border-stone-300 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 sm:p-6">
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold">Paket konten<select wire:model="paketId" class="mt-1.5 w-full rounded-xl border-stone-300 bg-stone-50 text-sm dark:border-zinc-700 dark:bg-zinc-950">@foreach($paket as $item)<option value="{{ $item->id }}">{{ $item->judul }}</option>@endforeach</select></label><label class="text-sm font-semibold">Template video<select wire:model="templateId" class="mt-1.5 w-full rounded-xl border-stone-300 bg-stone-50 text-sm dark:border-zinc-700 dark:bg-zinc-950">@forelse($templates as $item)<option value="{{ $item->id }}" @disabled($item->status !== 'aktif')>{{ $item->nama }} v{{ $item->versi }} · {{ $item->status }}</option>@empty<option value="">Belum ada template</option>@endforelse</select></label></div>
        <button type="button" wire:click="buatVideo" wire:loading.attr="disabled" class="mt-5 w-full rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white hover:bg-slate-700 disabled:opacity-50 dark:bg-amber-400 dark:text-amber-950">Buat video dari foto final</button>
    </section>
    <section class="mt-6 space-y-3"><h2 class="text-sm font-bold">Riwayat render</h2>@forelse($riwayat as $item)<article class="flex items-center justify-between gap-4 rounded-xl border border-stone-300 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div><strong class="text-sm">Video #{{ $item->id }}</strong><p class="mt-1 text-xs text-slate-500">{{ ucfirst($item->status) }} · {{ $item->created_at->diffForHumans() }}</p>@if($item->pesan_gagal)<p class="mt-2 text-xs text-red-600">{{ $item->pesan_gagal }}</p>@endif</div>@if($item->status === 'selesai')<button wire:click="unduh({{ $item->id }})" class="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white">Unduh MP4</button>@endif</article>@empty<div class="rounded-xl border border-dashed border-stone-400 px-4 py-10 text-center text-sm text-slate-500">Belum ada render video untuk paket ini.</div>@endforelse</section>
</main></div>
